### PR TITLE
A couple fixes and addons 

### PR DESCRIPTION
**Pull request by nodekra**
1.  `child_process.execFile  bin/deploy.sh `as root if `"sudo:true"` and invoke it by itself with "sudo -H"
2.  added "group" option, so execFile or sudo will run with `$user:$group`, instead of  `$user:root`
3.  pass $path and $branch to user task script for better deploy automation: `"start to run shell script: sh $task $path $branch"`
4.  moved log to /var/log dir

### CODE REVIEW

**Comment by mytharcher** [comment]
Thanks so much for improving this tool. There are some suggestion and question on this PR:
1. Not to change the indent when you just want to modify the logic. Or it will be hard to review the diff.
2. The feature of user task script I planned to deprecate it. Because by using the `.git/hooks/post-merge` script in any repository will be a better practice (noticed in #5 ).
3. I am not sure what scenario will you use the `extraArg`?

The feature about root user and group options looks great, I will merge this PR after your fixes.

Cheers

**Comment by nodekra** [comment]
Hi there, 
1. I'm sorry for such mistakes, my first PR and I did changes within github editor with copy-past of whole code from console. I have issues with git inside my IDE, will fix it.
2. looks correct, I will do it
3. I use few options for one branch, in my case it is: 
   - `"origin/dev" {"path": "/var/www/html" }`  
   - `"origin/dev/composer" {"path": "/var/www/html", "shell:" "bin/update_composer.sh", "sudo:" true }` 

1st will do git fetch only, 2nd will fetch changes as well as run additional task.
So we can do POST request to one branch, but with different tasks  `localhost:6060/project/id/dev` or `localhost:6060/project/id/dev/composer` . Howere I have done this logic inside user task script, but I think this extraArg still can be usefull.

I will back later with fixes. Thank you.

**Comment by mytharcher** [comment]
Yes. I have same problem as you. Sometimes we need to update composer/npm packages, but we don't want it run every time unless it is updated for saving task time. And I found a useful [gist:sindresorhus/7996717](https://gist.github.com/sindresorhus/7996717) there, for checking to run tasks base on updated items.

I think hookagent should just play a more common role as receiving post hook request and trigger the code update. But after new code updated, what tasks to be run should depend on each project.

And now I realized the parameters in post hook request is also a bad design. Because anyone will add only one post hook for a project to a server. Whatever the remote/branch parameters are, there can be only one, or there will be duplicated requests. A better way to avoid this while we want to make different branches to update their paths is, to analyze which branch/commit come from in the post data. This is also a thought in my mind but have no time to implement.

I think the parameters in post request URL should also be deprecated in some day. But in config file it could be kept for different paths. So, for the `extraArg` we should not waste more time on it.

**Comment by mytharcher** [comment]
Close due to deprecating feature and long time no updated.

**Pull request closed without merging**
